### ISSUE TITLE
Frontend posts sorted by date modified

### ISSUE THREAD

**Issue by paulschreiber** [iamsayan/wp-last-modified-info#10]
We have the settings like so:
![image](https://user-images.githubusercontent.com/86784/97027326-9190e780-1528-11eb-87fb-4bf65116ac61.png)

Despite this, frontend posts are being sorted by `post_modified` instead of `post_date`.

The workaround was to go to the settings page and click `Save Settings`, which forced a save of the settings.

I suspect the bug is here:
```php
if ( ! $this->is_equal( 'default_sort_order', 'default' ) ) {
	if ( ! is_admin() && $query->is_main_query() ) {
	    if ( $query->is_home() || $query->is_category() || $query->is_tag() ) {
	    	$query->set( 'orderby', 'modified' );
	    	$query->set( 'order', $front_order );
		}
	}
}
```

If `$this->get_data( 'lmt_' . $name )` returns an empty string, it says "oh, that's not the default, let's sort by date modified".

Adding a nonempty check would probably fix it:
```php
if ( $this->get_data( 'lmt_default_sort_order' ) && ! $this->is_equal( 'default_sort_order', 'default' ) ) {
```

**Comment by iamsayan** [comment]
Fixed in v1.8.0
