### ISSUE TITLE
How to replace post published date with post modified info?

### ISSUE THREAD

**Issue by oviliz** [iamsayan/wp-last-modified-info#2]
Hi, this is a nice plugin but I would really like to get the info inline with the other post information (author, category, comments number, etc.). Is this possible?

I read that it "Allows you to replace post published date with post modified info." so that suggests it should be possible. But I can't see how in the Settings.

**Comment by iamsayan** [comment]
Hi @oviliz 

Could you please give me the link of your website?

**Comment by oviliz** [comment]
Sorry, the website is in maintenance mode. What were you interested to look at?

**Comment by iamsayan** [comment]
> I read that it "Allows you to replace post published date with post modified info." so that suggests it should be possible. But I can't see how in the Settings.

Hi, you can do it from here.

![image](https://user-images.githubusercontent.com/25281493/59959830-32f2ce00-94dc-11e9-9a17-652a0db40a3c.png)

> What were you interested to look at?

It will be easy for me to help you by providing the code which you have to enter in the given screenshot. Thanks!

**Comment by sergiofslopes** [comment]
Hi, 
Thanks for the plugin, ti's all what I was looking for. I would like to give more relevance to the last modified data, but I don't want to leave the information on the content area. I want to show the last modified data along with the published data. 
Could you help me.  
My website https://www.osmeustrilhos.pt/

Thank you.
Sérgio
